password_project/password/basic_app/urls.py
from django.urls import path
from basic_app import views

app_name = 'basic_app'

urlpatterns = [
    path("registration/",views.registration,name='registration'),
    path("user_login/",views.user_login, name = 'user_login')
]

password_project/password/password/urls.py
from django.contrib import admin
from django.urls import path,include
from basic_app import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path("",views.index, name='index'),
    path("basic_app/",include('basic_app.urls')),
    path('logout/',views.user_logout,name='logout'),
    path('special/',views.special,name='special')
]

password_project/password/basic_app/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class UserProfileInfo(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to = 'profile_pics',blank=True)

    def __str__(self):
        return self.user.username

password_project/password/basic_app/forms.py
from django import forms
from django.contrib.auth.models import User
from basic_app.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget = forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username','email','password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site','profile_pic')

password_project/password/basic_app/views.py
from django.shortcuts import render
from basic_app.forms import UserForm, UserProfileInfoForm

from django.contrib.auth import authenticate,login, logout
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse,HttpResponseRedirect


# Create your views here.
def index(request):
    return render(request,"basic_app/index.html")

@login_required
def special(request):
    return HttpResponse("Logged In! Woaaahhh!")

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))


def registration(request):
    registered = False

    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data = request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit = False)
            profile.user = user

            if "profile_pic" in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()
            registered = True

        else:
            print(user_form.errors,profile_form.errors)

    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request,"basic_app/registration.html",{'user_form':user_form,'profile_form':profile_form,'registered':registered})



def user_login(request):


    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password = password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("Account Not Active!")
        else:
            print("Someone tried to login and failed!")
            print("Username: {}".format(username))
            return HttpResponse("Invalid Login Details Supplied!")

    else:
        return render(request, 'basic_app/login.html',{})

password_project/password/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

  </head>
  <body>
    <style >
    .jumbotron {
      padding: 2rem 1rem;
      margin-bottom: 2rem;
      background-color: #e9ecef;
      border-radius: .3rem;
      }
    </style>

    <nav class= "navbar navbar-expand-lg navbar-light bg-primary">
      <div class="container">
        <ul class="nav navbar-nav">
          <li> <a class="navbar-brand" href="{% url 'index' %}">DJANGO</a></li>
          <li> <a class="nav-link" href="{% url 'admin:index' %}">Admin</a></li>
          <li> <a class="nav-link" href="{% url 'basic_app:registration' %}">REGISTRATION</a></li>
          {% if user.is_authenticated %}
          <li> <a class="nav-link" href="{% url 'logout' %}">LOG OUT!</a>  </li>
          {% else %}
            <li> <a class = "nav-link" href="{% url 'basic_app:user_login'%}"> Login</a></li>
          {% endif %}
        </ul>

      </div>
    </nav>
    <div class="container">
      {% block body_block %}
      {% endblock %}

    </div>
  </body>
</html>

password_project/password/templates/basic_app/index.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
{% block body_block %}

  <div class="Segoe UI">
    <h1>Learning Website!</h1>
    <h2>Jealsous Huhhh?</h2>

  </div>
{% endblock %}

password_project/password/templates/basic_app/login.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
{% block body_block %}

  <div class="jumbotron">
    <h1>Please Login!</h1>

    <form action="{% url 'basic_app:user_login' %}" method="post"></form>
      {% csrf_token %}
       <label for="username">UserName</label>
       <input type="text" name="username" placeholder="Enter your name!">

       <label for="password">Password</label>
       <input type="password" name="password" placeholder="Enter your password!">

       <input type="submit" name="" value="Login">

  </div>






{% endblock %}

password_project/password/templates/basic_app/registration.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
{% load static %}
{% block body_block %}
<div class="container">
  {% if registered %}
    <h1>Thank you! Registered!</h1>
  {% else %}
    <h1>Register Here!</h1>
    <h3>Fill out the form!</h3>

    <form enctype="multipart/form-data" method="post">
        {{ user_form.as_p }}
        {{ profile_form.as_p }}
        {% csrf_token %}

        <input type="submit" name="" value="Register">

    </form>
    {% endif %}
</div>
{% endblock %}